"""varsapradaya device readings history

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-01 16:09:01.141683
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_readings',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('parameter', sa.String(length=40), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_on', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'parameter', 'observed_at')
    )
    op.create_index(op.f('ix_device_readings_device_id'), 'device_readings', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_readings_observed_on'), 'device_readings', ['observed_on'], unique=False)
    op.create_index(op.f('ix_device_readings_org_id'), 'device_readings', ['org_id'], unique=False)
    op.create_index(op.f('ix_device_readings_parameter'), 'device_readings', ['parameter'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_readings_parameter'), table_name='device_readings')
    op.drop_index(op.f('ix_device_readings_org_id'), table_name='device_readings')
    op.drop_index(op.f('ix_device_readings_observed_on'), table_name='device_readings')
    op.drop_index(op.f('ix_device_readings_device_id'), table_name='device_readings')
    op.drop_table('device_readings')
    # ### end Alembic commands ###
