"""farmfuture farm import and device readings

Farm.postal_code and Farm.notes (filled by the Varsapradaya farm import), a filtered unique index on
(org_id, external_farm_id), and Device.latest_readings (the latest value from a Varsapradaya device).

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 14:41:23.322727
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('latest_readings', sa.JSON(), nullable=True))
    op.add_column('farms', sa.Column('postal_code', sa.String(length=20), nullable=True))
    # Existing farms get an empty note (the model default); the server default makes that possible on a table with rows.
    op.add_column('farms', sa.Column('notes', sa.Text(), nullable=False, server_default=sa.text("''")))
    # One farm per Varsapradaya farm in an organisation. Filtered, so farms without one are not limited
    # (a plain unique index on SQL Server would allow only one NULL).
    op.create_index('uq_farms_org_external_farm_id', 'farms', ['org_id', 'external_farm_id'], unique=True, mssql_where=sa.text('external_farm_id IS NOT NULL'), sqlite_where=sa.text('external_farm_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_farms_org_external_farm_id', table_name='farms', mssql_where=sa.text('external_farm_id IS NOT NULL'), sqlite_where=sa.text('external_farm_id IS NOT NULL'))
    op.drop_column('farms', 'notes', mssql_drop_default=True)
    op.drop_column('farms', 'postal_code')
    op.drop_column('devices', 'latest_readings')
    # ### end Alembic commands ###
